# Generated by Django 2.1.1 on 2018-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0002_auto_20180920_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime_recorded', models.DateTimeField(verbose_name='datetime recorded')),
            ],
        ),
    ]
